apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-app
  template:
    metadata:
      labels:
        app: microservice-app
    spec:
      containers:
      - name: microservice-app
        image: dockerhub_username/microservice-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-app-service
spec:
  selector:
    app: microservice-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
